# Generated by Django 5.1.2 on 2024-11-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0002_remove_customuser_sustainability_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation",
            name="created_at",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="metadata",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="tags",
            field=models.TextField(default="general"),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="user_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
