# Generated by Django 5.1.2 on 2024-11-23 05:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0003_remove_recommendation_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useractivity",
            old_name="date",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="user_rating",
        ),
        migrations.RemoveField(
            model_name="savedrecommendation",
            name="saved_at",
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recommendation",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="recommendations/"
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="impact_level",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                default="Low",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedrecommendation",
            name="date_saved",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="category",
            field=models.CharField(
                choices=[
                    ("Energy", "Energy"),
                    ("Water", "Water"),
                    ("Waste", "Waste"),
                    ("Transportation", "Transportation"),
                    ("Food", "Food"),
                    ("Sustainable Living", "Sustainable Living"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="savedrecommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="action",
            field=models.CharField(
                choices=[
                    ("Goal Set", "Goal Set"),
                    ("Recommendation Viewed", "Recommendation Viewed"),
                    ("Recommendation Saved", "Recommendation Saved"),
                    ("Goal Progress Updated", "Goal Progress Updated"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Energy", "Energy"),
                            ("Water", "Water"),
                            ("Waste", "Waste"),
                            ("Transportation", "Transportation"),
                            ("Food", "Food"),
                            ("Sustainable Living", "Sustainable Living"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target", models.CharField(max_length=255)),
                (
                    "progress",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Energy", "Energy"),
                            ("Water", "Water"),
                            ("Waste", "Waste"),
                            ("Transportation", "Transportation"),
                            ("Food", "Food"),
                            ("Sustainable Living", "Sustainable Living"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CarbonFootprint",
        ),
    ]
