# Generated by Django 5.1.2 on 2024-11-23 17:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recommendations",
            "0005_remove_profile_user_remove_userpreferences_user_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("recommendation_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="savedrecommendation",
            name="recommendation",
        ),
        migrations.RemoveField(
            model_name="savedrecommendation",
            name="user",
        ),
        migrations.RenameField(
            model_name="carbonfootprint",
            old_name="month",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="carbonfootprint",
            old_name="amount",
            new_name="footprint",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="description",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="user_rating",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="impact",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recommendations.category",
            ),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="SavedRecommendation",
        ),
    ]
