# Generated by Django 5.1.2 on 2024-11-30 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0008_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation",
            name="category",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="savedrecommendation",
            name="recommendation",
        ),
        migrations.RemoveField(
            model_name="savedrecommendation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="user",
        ),
        migrations.DeleteModel(
            name="CarbonFootprint",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="Recommendation",
        ),
        migrations.DeleteModel(
            name="SavedRecommendation",
        ),
        migrations.DeleteModel(
            name="UserActivity",
        ),
    ]
