# Generated by Django 5.1.2 on 2024-12-01 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0010_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="user",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="carbon_saved",
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recommendation",
            name="difficulty",
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recommendation",
            name="impact",
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="SavedRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommendations.recommendation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
