# Generated by Django 5.1.2 on 2024-12-01 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0011_remove_category_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="carbon_saved",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recommendations.category",
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="difficulty",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="impact",
            field=models.CharField(max_length=255),
        ),
    ]
