# Generated by Django 5.1.2 on 2024-12-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0012_recommendation_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="category",
            field=models.CharField(max_length=100),
        ),
    ]
