# Generated by Django 5.1.2 on 2024-12-02 05:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0013_alter_recommendation_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savedrecommendation",
            unique_together={("user", "recommendation")},
        ),
    ]
