# Generated by Django 5.1.2 on 2024-12-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0014_alter_savedrecommendation_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savedrecommendation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="savedrecommendation",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
